site_name: kangaroo-builder.com
theme:
  logo: assets/kangaroo.png
  name: material
  palette:
    scheme: default
    primary: sky
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.footer
  copyright: "2025 Kangaroo Builder"
nav:
  - About: about.md
  - Getting Started: installation.md
  - Builder:
     - Basics: builder/builderBasics.md
     - Workflow Tricks: builder/workflowTricks.md
     - JSON Editor: builder/jsonEditor.md
  - Puppet:
      - General: puppet/puppetGeneral.md
      - Limbs Reference: puppet/puppetLimbs.md
      - Bell Collider: puppet/bellCollider.md
      - Dynamics: puppet/dynamics.md
      - Puppet Tweaker Ctrls: puppet/tweakerCtrls.md
  - Body:
      - Deformations: body/deformations.md
      - Pose Editor: body/poseEditor.md
      - Motion Capture: body/motionCapture.md
  - Face:
      - General: face/faceGeneral.md
      - Shape Editor: face/shapeEditor.md
      - Eyes: face/eyes.md
      - Brows: face/brows.md
      - Mouth: face/mouth.md
      - Squash/Stretch: face/squashStretch.md
      - Face Tweaker Ctrls: face/faceTweakerCtrls.md
  - Python: python.md
  - Tools: tools.md
  - Animator Tools: picker.md
  - Model Changes: modelChange.md
  - Game Engines: gameEngines.md
  - FAQ: FAQ.md
  - License: license.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - attr_list

#extra_css:
#  - extra.css
extra_javascript:
  - javascripts/scroll-behavior-toggle.js