site_name: Kangaroo-Builder
nav:
  - About: about.md
  - Getting Started: installation.md
  - Builder: builder.md
  - Puppet: puppet.md
  - Body: body.md
  - Face: face.md
  - Python: python.md
  - Tools: tools.md
  - Picker: picker.md
  - Model Change: modelChange.md
  - FAQ: FAQ.md
  - License: license.md