site_name: kangaroo-builder.com
theme:
  logo: images/evilKangaroo_100.png
  name: material
  palette:
    scheme: default
    primary: sky
  font:
    text: Roboto
    code: Roboto Mono
  custom_dir: overrides
  features:
    - navigation.footer
  footer: false
  copyright: "2025 Kangaroo Builder"
  favicon: images/favicon.png

nav:
  - Home: index.md
  - Getting Started: gettingStarted.md
  - Builder:
     - General: builder/builderGeneral.md
     - Workflow Tricks: builder/workflowTricks.md
     - JSON Editor: builder/jsonEditor.md
  - Puppet:
      - General: puppet/puppetGeneral.md
      - Limbs Reference: puppet/limbsReference.md
      - Bell Collider: puppet/bellCollider.md
      - Dynamics: puppet/dynamics.md
      - Puppet Tweaker Ctrls: puppet/tweakerCtrls.md
  - Body:
      - Deformations: body/deformations.md
      - Motion Capture: body/motionCapture.md
      - Pose Editor I: body/poseEditor1.md
      - Pose Editor II: body/poseEditor2.md
  - Face:
      - General: face/faceGeneral.md
      - Eyes: face/eyes.md
      - Brows: face/brows.md
      - Mouth: face/mouth.md
      - Squash/Stretch: face/squashStretch.md
      - Face Tweaker Ctrls: face/faceTweakerCtrls.md
      - Shape Editor I: face/shapeEditor1.md
      - Shape Editor II: face/shapeEditor2.md

  - Python: 
        - Python I: python/python1.md
        - Python II: python/python2.md
        - Library: python/pythonLibrary.md
  - Tools: 
      - SkinCluster: tools/toolsSkinCluster.md
      - Weightmaps: tools/toolsWeightmaps.md
      - Geometry: tools/toolsGeometry.md
      - Deformer Import: tools/toolsDeformerImport.md
      - Plane Cutter: tools/toolsPlaneCutter.md
  - Animator Tools: picker.md
  - Model Change: modelChange.md
  - Game Engines: gameEngines.md
  - Model Naming Convention: modelNamingConvention.md
  - FAQ: FAQ.md
  - License: license.md
  - Download: download.md
  - Contact: contact.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - attr_list

extra_css:
  - extra2.css
extra_javascript:
  - javascripts/scroll-behavior-toggle.js